interface=wlan0        # Твой Wi-Fi адаптер (проверь через ip link)
listen-address=192.168.5.1
bind-interfaces
domain-needed
bogus-priv
# Вот тут магия: привязываем имя к IP сервера
address=/ucitel.skola/192.168.5.1
dhcp-range=192.168.5.50,192.168.5.150,12h
